filecoin-project/bellperson

- src/multicore.rs
This is to make it easier to experiment with this, when using it in different settings.
> feat: allow controll of the maximum number of cpus using BELLMAN_NUM_CPUS

- .circleci/config.yml
- Cargo.toml
- src/domain.rs
- src/gpu/fft.rs
- src/gpu/multiexp.rs
- src/gpu/utils.rs
- src/lib.rs
- src/multiexp.rs
The PR fixes some of the problems that were preventing the library to run on virtual machines (CircleCI) and machines without GPUs.
> Fix bugs/tests

- .circleci/config.yml
- Cargo.toml
- src/gpu/utils.rs
Note: It currently uses a git dependency for fetching `ocl`.
> Use forked ocl with a calm Platform::list()

- Cargo.toml
- src/domain.rs
- src/gpu/multiexp.rs
- src/gpu/utils.rs
- src/groth16/prover.rs
- src/lib.rs
- src/multiexp.rs
This PR tries to implement auto-detection of best GPU parameters for multiexp algorithm based on the card name and input size.
> feat(gpu): automatic detection of optimal GPU params

- Cargo.toml
- src/gpu/mod.rs
- src/gpu/utils.rs
- src/groth16/prover.rs
This PR extracts the GPU locking out of https://github.com/filecoin-project/bellman/pull/30. It's the same code with the only functional change that it propagates up a result instead of panicking.
> feat: add cross process GPU locking

- README.md
- src/gpu/utils.rs
https://github.com/filecoin-project/bellman/issues/24
> feat(gpu): support more gpus

- README.md
- src/domain.rs
- src/groth16/prover.rs
- src/multiexp.rs
> refactor(gpu): remove correctness checks 

- src/groth16/prover.rs
- src/lib.rs
Good to know for debugging purposes.
> feat: report version when running prover

- src/gpu/locks.rs
- src/gpu/nogpu.rs
Do not switch to CPU when GPU is occupied!
> feat(gpu): block low-prio process till gpu is ready again

- src/gpu/common/field.cl
- src/gpu/sources.rs
Results in a ~5% improvement in speed
> feat(gpu): generate inline-asm version of FIELD_add_ and FIELD_sub_

- src/gpu/multiexp/multiexp.cl
5-10% faster than the previous version depending on the input size.
> feat(gpu): weird optimization

- src/gpu/common/field.cl
Inspired from:
https://www.microsoft.com/en-us/research/wp-content/uploads/1998/06/97Acar.pdf
https://hackmd.io/@zkteam/modular_multiplication
Thanks to @dignifiedquire for finding this.
> feat(gpu): switch to CIOS montgomery reduction

- src/lib.rs
- src/multiexp.rs
- src/util_cs/bench_cs.rs
- src/util_cs/metric_cs.rs
- src/util_cs/mod.rs
- src/util_cs/test_cs.rs
The refactor here was the intended final commit of #86. @dignifiedquire approved the previous without knowing this was to replace it (and I did not notice it had not been pushed either).
This PR is a fixup for that.
> Hopefully final cleanup/fix of density tracker extend.

- src/util_cs/metric_cs.rs
The code for the pretty printing is taken from
https://github.com/filecoin-project/rust-fil-proofs/pull/1131.
> feat: better pretty printing for circuits

- src/gadgets/multipack.rs
Extracted from `rust-fil-proofs/storage-proofs-core`
> feat(gadgets): add multipack::pack_bits

- .circleci/config.yml
These are preparations for the code coverage work.
> Ci small refactor

- src/gpu/locks.rs
- src/gpu/multiexp.rs
- src/groth16/prover.rs
- src/multicore.rs
- src/multiexp.rs
A new day a new PR.
We are getting closing fixing all deadlocks and race conditions. This PR take the code from the the previous attempts at #147, #148, #149 and re-arranges them into known good ones and bad ones. The first few commits are known to be good and pass CI (at least the tests, the coverage fails, that's something to look into next). Those are the commits up to (including) https://github.com/filecoin-project/bellperson/commit/e6f32da78f22b308f72589b2a8a5ff3cfb5094c8
Though there is still a potential deadlock left in the GPU code path. The newer commits try to fix that one, but doesn't succeed as can be seen on the failing CI.
> Deadlock bug fix v4

- Cargo.toml
- src/groth16/mapped_params.rs
- src/multicore.rs
feat: update blstrs dependency version
style: remove verbose logging
Replaces #156
> feat: parallelize mapped parameter loading

- README.md
- src/groth16/prover.rs
docs: update README with test examples
> fix: remove logging warning when not using gpu feature

- README.md
Added following GPUs 3090, 3080, 3070, gfx906
Based on https://github.com/filecoin-project/bellperson/blob/master/src/gpu/utils.rs
> Add updated tested GPUs to README.md

- src/groth16/aggregate/prove.rs
- src/groth16/aggregate/verify.rs
- tests/groth16_aggregation.rs
This PR allows to include any inputs to the transcript. Specifically, we should always input the public inputs but since these are costly we only intend to include the non fixed part that is used to derive a portion of the public inputs.
@cryptonemo : the value to pass in `transcript_include`now  is the seed(s) of the randomness used to derive the challenges for provecommit .
**The vuln:** 
If a miner can change one part of the public inputs to a specific value  that are passed to the verification algorithm of Snarkpack, he can take the aggregated proof of someone else and make it pass like its own. He would still have to make the precommits though (given all parameters are loaded from the chain) and then can submit the aggregated prove commit of someone else (so doesn't need to compute …
> SnarkPack: allow elements as inputs to transcript

- examples/verifier_bench/Cargo.toml
- src/groth16/aggregate/prove.rs
- src/groth16/aggregate/transcript.rs
- src/groth16/aggregate/verify.rs
> fixes: audit snarkpack aggregation

- src/groth16/aggregate/accumulator.rs
Spawn the thread that is receiving messages outside the Rayon thread
pool, so that it can always receive messages, even if the thread pool
is fully occupied. If many senders are spawn before the receiver, there
will be a deadlock.
To illustrate the issue, run the `test_groth16_aggregation` with a
thread pool of size 1. Prior to this change, the test deadlocks:
RAYON_NUM_THREADS=1 cargo test --release --tests test_groth16_aggregation -- --exact --nocapture
> fix: prevent potential deadlock

- src/gpu/locks.rs
Trying to use an exclusive lock, means that the file is actually getting locked
exclusively, even if we just want to check if there is an exclusive lock.
Additionally we now check for the correct error when checking the lock
> fix(gpu): use shared locks to check for an exclusive lock

- src/test_utils.rs
This part of the code is based on a StackOverflow answer.
> chore: credit where credit is due

- src/gpu/locks.rs
The GPU lock makes sure that only one kernel at a time operates on the
GPU. Hence it's important that the GPU lock exists as long as there is
a kernel associated with the GPU. But it also shouldn't last longer
than needed.
This commit fixes a bug, where the GPU lock was hold too long. It was
hold until the locked kernel would've been dropped, but it only needs
to last as long as the actual kernel lives.
> fix: release the GPU lock reliably

- Cargo.toml
- build.rs
- src/groth16/multiscalar.rs
- src/lib.rs
> feat: support aarch64 on rust stable

- src/constraint_system.rs
> chore: add Rustdoc for new trait members

- src/groth16/tests/mod.rs
- src/lc.rs
Backport of https://github.com/zkcrypto/bellman/pull/78
Fixes #271
> Backport of zkcrypto fix for Zero coefficient bug

- .circleci/config.yml
- Cargo.toml
- src/groth16/ext_supraseal.rs
- src/groth16/mod.rs
- src/groth16/params.rs
- src/groth16/proof.rs
- src/groth16/prover/mod.rs
- src/groth16/prover/native.rs
- src/groth16/prover/supraseal.rs
- src/groth16/supraseal_params.rs
- src/lib.rs
- tests/dummy_engine.rs
- tests/groth16.rs
- tests/groth16_aggregation.rs
- tests/mimc.rs
- tests/minroot.rs
- tests/util.rs
This is about adding using [Supranationals SupraSeal C2](https://github.com/supranational/supra_seal/tree/main/c2) in bellperson.
> Using SupraSeal C2

- src/gpu/locks.rs
- src/gpu/multiexp.rs
- src/groth16/aggregate/prove.rs
- tests/minroot.rs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- tests/groth16_aggregation.rs
---
- Corrected minor typos in comments for clarity.
---
> chore: fix typos in groth16_aggregation.rs test

- src/gpu/locks.rs
- src/groth16/mapped_params.rs
- src/groth16/prover/native.rs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in files
