filecoin-project/bellperson

Cargo.toml
src/domain.rs
src/gpu/common/defs.cl
src/gpu/common/field.cl
src/gpu/error.rs
src/gpu/fft.rs
src/gpu/fft/fft.cl
src/gpu/mod.rs
src/gpu/multiexp.rs
src/gpu/multiexp/ec.cl
src/gpu/multiexp/exp.cl
src/gpu/multiexp/field2.cl
src/gpu/multiexp/multiexp.cl
src/gpu/nogpu.rs
src/gpu/sources.rs
src/gpu/structs.rs
src/groth16/generator.rs
src/groth16/prover.rs
src/lib.rs
src/multiexp.rs

This PR from @finalitylabs adds GPU accelerated versions of the Fast-Fourier-Transform and Multi-Exponentiation (For Bls12-381 engine) algorithms to the great Bellman library :) The `ocl` feature is turned on by default and can be disabled.
Let us know if any changes are needed before merging. @dignifiedquire
@nginnever, @keyvank

feat: implement GPU FFT & Multiexp

---

src/gpu/multiexp.rs

This lets cards other than RTX2080Ti to flawlessly run the GPU kernels.

fix(gpu): let the card choose workgroup size

---

src/gpu/multiexp.rs

This PR fixes `mimc` and `serialization` tests. The failures were caused by some bugs in the multigpu implementation of multiexp.

Fix multigpu

---

src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/groth16/prover.rs
src/multiexp.rs

This commit allows arbitrarily sized multiexp instances to run on multiple GPUs. Notice that the parameters are customized for 2080Ti cards and may not work properly on other cards.

Fixed chunk-size for GPU Multiexp

---

.gitignore
Cargo.toml
src/domain.rs
src/gpu/fft.rs
src/gpu/mod.rs
src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/gpu/sources.rs
src/gpu/utils.rs
src/groth16/prover.rs
src/multiexp.rs

~~Now it lazily instantiates Bls12-381 kernels in a global static variable and uses them instead of compiling the kernels each time `create_proof` is called.~~
UPDATE: Now, instead of having global static ProQues, we have combined the source code of FFT and Multiexp kernels. This makes the Multiexp and FFT kernel objects use the same codes and thus it enables the Nvidia driver to cache the whole binary once, making compilation times near zero.
Other changes:
- CHUNK_SIZE is now 8,388,608 (Allowing wider variety of NVIDIA cards to run support this work)
- It doesn't print the panic logs anymore (Solving https://github.com/filecoin-project/rust-fil-proofs/issues/931)
**Issues:**
- ~~Curves other than Bls12-381 are going to conflict with the static global variable mentioned since it is only …

feat(gpu): instantiates Bls12-381 devices once and share kernels

---

src/groth16/prover.rs

This simply removes the GPU computation of the a_aux multiexp that is broken so that the rest of the prover can continue in the mean time.

fix: move bad multiexp from GPU to CPU

---

src/gpu/utils.rs

The `BELLMAN_CUSTOM_GPU` environment variable allows you to run bellman prover on GPUs that are not explicitly supported in the current version of bellman library.
Usage:
```> BELLMAN_CUSTOM_GPU="<card name>:<cuda cores>,<card name>:<cuda cores>,..."```
`<card name>` can be found through running `clinfo` command, shown after `Device Name`.
`<cuda cores>` is also available in official specifications of that card.
E.g.
You can add Nvidia GeForce GTX 1050Ti like this:
```> BELLMAN_CUSTOM_GPU="GeForce GTX 1050 Ti:768"```
References:
https://github.com/filecoin-project/bellman/issues/24

feat(gpu): enable custom gpus

---

src/domain.rs
src/multiexp.rs

Checking the correctness of GPU results can be time consuming, which may invalidate the benchmarking results of other crates that use bellman library. User can disable this feature using `BELLMAN_GPU_NO_CHECK` flag.

feat(gpu): env var for disabling gpu validity check

---

src/lib.rs

With exposing `gpu::GPU_NVIDIA_DEVICES` to the public API, you can get
a list of GPU devices that are supported on your machine.

feat(gpu): make GPU_NVIDIA_DEVICES public

---

src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/gpu/utils.rs
src/groth16/prover.rs
src/multiexp.rs

Choose dynamic chunk-size for each card based on its memory instead of using a fixed one. This would allow the bellman library to support cards with smaller memories, and also use the full potential of cards with larger memories. It also makes the bellman library to choose the GPU parameters (num-windows/num-groups) per multiexp, instead of calculating a fixed one per kernel initialization.
This PR introduces a tiny performance increase of x1.03 for a 130mm circuit on a machine with x2 2080Tis. (362s vs 370s)

feat(gpu): dynamic gpu parameters

---

src/domain.rs
src/groth16/generator.rs
src/groth16/prover.rs
src/lib.rs
src/multiexp.rs

You can now catch the `GPUError`s as a results of the `create_proof` function.

feat(gpu): remove panics and propagate all gpu errors

---

src/gpu/multiexp.rs
src/groth16/prover.rs
src/lib.rs

This PR contains better log messages about why kernels aren't instantiating. This way `multiexp NOT supported` isn't the only message logged when kernel instantiation fails.

feat(gpu): better error logging

---

src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/multiexp.rs

User can now choose what percent of the bases/exps he would like to be calculated on CPU through an environment variable called `BELLMAN_CPU_UTILIZATION`. Default value is 0 and user can set this to any value in the range of 0 and 1 (0 means all on GPU and 1 means all on CPU)
Best ratio can be found using trial and error.

feat(gpu): cpu utilization for gpu multiexp 

---

src/domain.rs

This would fix FFT kernel instantiation problem for small sets.

fix(gpu): test size no bigger than kernel size

---

.circleci/config.yml
Cargo.toml
README.md
src/domain.rs
src/multiexp.rs

This also removes the gpu-test feature and requires that cirlceci machine builds with a supported nvidia gpu.

feat: add Circleci gpu config

---

Cargo.toml
src/gpu/error.rs
src/gpu/fft.rs
src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/gpu/utils.rs
src/lib.rs

we had an accidental recursion in the manual implementation,
fixed now and switched to a library to avoid it in the future

refactor: switch error handling to use thiserror

---

src/domain.rs
src/gpu/error.rs
src/gpu/fft.rs
src/gpu/locks.rs
src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/gpu/utils.rs
src/groth16/prover.rs
src/multiexp.rs
tests/gpu_provers.rs

Previously, kernels were only being dropped between full multiexp rounds, whereas the priority lock can be seen sooner (In between the full multiexp rounds)
This PR changes the structure of `GPUError`, adding a new `GPUTaken` kind of error, which is raised when priority lock is seen in chunked multiexp rounds, thus the gpu lock gets released sooner than before.

feat(gpu): drop kernels as soon as priority lock is seen 

---

src/gadgets/num.rs
src/lib.rs

This PR adds support for:
+ Adding two Nums.
+ Scaling a Num by a scalar.
+ When adding a variable to LinearCombinations, coalescing with any existing component for that variable.

feat: add support adding/scaling Num. Simplify when adding LCs.

---

src/groth16/mod.rs
src/groth16/prover.rs
src/multicore.rs

Uses the existing env variable to restrict the number of threads used for parallel proving.
Cleaned up version of #81

feat(groth16): control parallel proving threads

---

README.md
src/gpu/utils.rs

Got this output from the v27 benchmark initially;
```
2020-06-09T14:00:38.426 INFO bellperson::groth16::prover > Bellperson 0.8.0 is being used!
2020-06-09T14:00:38.901 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-06-09T14:00:39.121 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
2020-06-09T14:00:39.122 INFO bellperson::gpu::fft > FFT: Device 0: Quadro M5000
2020-06-09T14:00:39.122 INFO bellperson::domain > GPU FFT kernel instantiated!
2020-06-09T14:00:39.488 INFO bellperson::gpu::locks > GPU is available for Multiexp!
2020-06-09T14:00:39.877 WARN bellperson::multiexp > Cannot instantiate GPU Multiexp kernel! Error: GPUError: No working GPUs found!
2020-06-09T14:00:40.329 INFO bellperson::gpu::locks > GPU is available for Multiexp!
2020-06-09T14:00:40.670 …
```

Add Quadro M5000 graphics card to list

---

src/gadgets/test/mod.rs
src/groth16/generator.rs
src/groth16/prover.rs
src/lib.rs
src/multiexp.rs

This PR adds a mechanism for concatenating independent constraint systems so circuit synthesis which can be performed in parallel — when the circuit in question can be decomposed to meet these constraints.

Add extend ConstraintSystem method, implement for ProvingAssignment.

---

Cargo.toml
src/gpu/fft.rs
src/gpu/multiexp.rs
src/gpu/utils.rs
src/groth16/prover.rs

This PR adds truly minimal benchmarking output to simplify measurement and optimization of proving.
It also upgrades to `rust-gpu-tool` v0.2.0, which seems to fix some slow downstream CI issues — although it's unclear why.
Here is the CI run which consumes this branch: https://app.circleci.com/pipelines/github/filecoin-project/rust-fil-proofs/2614/workflows/1b7eaf56-12ab-45b9-b0f7-7403af57821c
For comparison, here is the slow CI run which differs only by this commit: https://app.circleci.com/pipelines/github/filecoin-project/rust-fil-proofs/2482/workflows/85ccd4f7-1f7f-4054-bf1b-27a6aeb311fa
Overview (for easiest comparison) here:  https://app.circleci.com/pipelines/github/filecoin-project/rust-fil-proofs?branch=bellperson-tests

Add proof-benchmarking output.

---

Cargo.toml
README.md

Also change the default features to juse `pairing` which itself enables
the `groth16` feature. This way it's clearer that there is a single
default feature you can swap out with `pairing` if you disable the
default features.

docs: explain compile-time features a bit better

---

src/groth16/multiscalar.rs

This fixes compilation error on aarch64 platform.
For the 1st parameter of _prefetch `p`, we need to cast the template type `* const T` to `* const i8`.
Error message:
```
error[E0308]: mismatched types
--> /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/bellperson-0.11.0/src/groth16/multiscalar.rs:268:19
|
265 | fn prefetch<T>(p: *const T) {
|             - this type parameter
...
268 |         _prefetch(p, _PREFETCH_READ, _PREFETCH_LOCALITY3);
|                   ^ expected `i8`, found type parameter `T`
|
= note: expected raw pointer `*const i8`
found raw pointer `*const T`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: could not compile `bellperson`
```

fix: aarch64 correct casting for prefetch

---

Cargo.toml
src/lib.rs

The previously used HashMap by aHash can be greatly improved by using std HashMap and FxHash, Using [rustc-hash](https://github.com/rust-lang/rustc-hash) will be 4x faster than ahash in circuit synthesis.

perf: use better FxHash instead of aHash to speed up circuit computation

---

src/domain.rs
src/multiexp.rs

The `gpu_fft_consistency()` test takes a long time to run. It is run
24 times, increasing the size by factor 2.
On CI the output looks like that:
```
test domain::tests::gpu_fft_consistency ... [2020-12-17T15:59:02Z INFO  bellperson::gpu::utils] Device: Device { brand: Nvidia, name: "Tesla T4", memory: 15843721216, bus_id: 0, platform: Platform(PlatformId(0x55af1c5ca8b0)), device: Device(DeviceId(0x55af1c5ca980)) }
[2020-12-17T16:00:03Z INFO  bellperson::gpu::fft] FFT: 1 working device(s) selected.
[2020-12-17T16:00:03Z INFO  bellperson::gpu::fft] FFT: Device 0: Tesla T4
Testing FFT for 2 elements...
GPU took 0ms.
CPU (8 cores) took 0ms.
Speedup: xNaN
============================
Testing FFT for 4 elements...
GPU took 0ms.
CPU (8 cores) took 0ms.
Speedup: xNaN
============================ …
```

test: reduce iterations

---

.circleci/config.yml
Cargo.toml
src/lib.rs
tests/gpu_provers.rs

The doc test runs a long time when coupled with code coverage instrumentation,
hence disable it.
First #137 and #138 should be merged, then this one should be rebased.
The tests are flaky, it seems unrelated to the code-coverage changes. I suspect that sometimes they deadlock for some reason. This should surely be investigated if it's a re-ocuring thing, but it's out of scope for this PR and I don't think this PR should be blocked by those problems.

Create code coverage reports

---

Cargo.toml
src/gpu/fft.rs
src/gpu/multiexp.rs
src/gpu/utils.rs

This change has nothing todo with my opencl3 work, it just updates to the latest ocl based version (to make future PRs simpler).

chore: upgrade to latest rust-gpu-tools

---

src/groth16/aggregate/accumulator.rs
src/groth16/aggregate/verify.rs

This is an incremental refactor of the work in #167.
It moves tracking of randomization into`PairingCheck`, where it belongs. It also refactors `merge_parts` to the more general `merge_equation` and adjusts tracking of the need for randomization atomically — so all checks merged in a single operation either require randomization or not. This allows the Groth16 equation to be exempted (once) just as we want. Likewise, `PairingChecks` now tracks precisely whether or not it has absorbed any non-random `PairingCheck`s. So the only way to successfully merge non-random `PairingCheck`s is in a single operation. In the case of our verification routines, this is done with `merge_equation` — but there is nothing to stop callers from accurately using `merge_one` (once) or any of the other `merge_…` …

Enforce all-but-once randomization more generally.

---

src/groth16/prover.rs

The assignments are moved out of the prover, afterwards it doesn't
contain any, hence their length inside the prover 0. Get the length
from the input assigments instead.
This commit makes the rebased version work.

Use correct input length

---

.circleci/config.yml

The Codecov upload doesn't work when the standard image for the
GPU instances is used. It makes sense to move away from Codecov
anyway, so let's disable it for now until we have an alternative.

chore: disable coverge reporting

---

src/groth16/mod.rs

The `DummyEngine` doesn't work on GPUs. It is using `Fr` for G1/G2, but the
GPU kernels don't support `Fr` calculations. Hence make sure that the
tests using the `DummyEngine` are not run when the `gpu` feature is enabled.
Closes #160.
This might not be the fix we want to do, but as I already have the code, I make a PR out of it :)

test: don't run groth tests on GPU

---

src/gpu/fft.rs
src/gpu/multiexp.rs

Macros are often used to reduce the boilerplate code to write. In case
of the kernel call the actual code isn't that much different from the
macro call.
A reader of the source code might suspect something complex going on in
the macro, although it's really straight forward. Hence I decided to
just replace the macro call with the actual code.
This also eases future uses of the call as type errors won't be hidden
within a macro, but will just be regular errors.

refactor: replace macro call with function call

---

src/groth16/aggregate/commit.rs
src/groth16/aggregate/macros.rs
src/groth16/aggregate/prove.rs
src/groth16/aggregate/srs.rs
src/groth16/aggregate/verify.rs

This PR brings the paper and the implementation in synchrony.
* When we first devised the protocol we started with the bases of the commitment keys shifted: `g^a` and `h^a^{n+1}` (and same with exponent `b`).However, we later realized we could move the bases to `g` and `h^a^n`, so we wrote it in this way in the paper. This change allows us to use the maximum aggregated proofs len (2^20 vs 2^19) when using the trusted setup from Filecoin and Zcash.
* This PR use domain separated hash functions in the respective places
* This PR changes the commitment polynomial so we use the KZG as a black box, using bases g and h directly.

IPP - Bring implementation in sync with paper 

---

src/groth16/aggregate/accumulator.rs

The channel messages are sent to might have been intentionally been
closed. Don't error if that is the case.
Closes #197.

fix: don't panic if channel was intentionally closed

---

src/lib.rs

Using the `pairing` and `blst` features together produces lots of
errors. This compile time error might help at least a bit to figure
out what is wrong.
The build error looks like this:
error: pairing and blst features are mutually exclusive. Running with --no-default-features might help.
--> src/lib.rs:140:1
|
140 | compile_error!("pairing and blst features are mutually exclusive. Running with --no-default-features might help.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

chore: add compile error for mutually exclusive features

---

Cargo.toml
src/gpu/fft.rs
src/gpu/multiexp.rs

Upgrade to a version of rust-gpu-tools that is using `opencl3` instead
of `ocl`.
The local work size is now explicitly set and not longer automatically
determined by the OpenCL implementation.

feat: use opencl3 based rust-gpu-tools

---

Cargo.toml
src/domain.rs
src/gpu/multiexp.rs
src/groth16/aggregate/macros.rs
src/groth16/aggregate/srs.rs
src/groth16/aggregate/verify.rs
src/groth16/generator.rs
src/groth16/proof.rs
src/groth16/prover.rs
src/groth16/verifier.rs
src/multicore.rs

In testing this removes the observed deadlocks in all cases so far. The thread pool does not use job stealing, and is much simpler. 
We will need to do benchmarks to see if there is any performance loss at the e2e perf.

fix: use yastl for thread pools instead of rayon

---

.circleci/config.yml
Cargo.toml
README.md
build.rs
src/domain.rs
src/gpu/error.rs
src/gpu/fft.rs
src/gpu/fft/fft.cl
src/gpu/mod.rs
src/gpu/multiexp.rs
src/gpu/multiexp/multiexp.cl
src/gpu/program.rs
src/gpu/sources.rs
src/gpu/utils.rs
src/groth16/mod.rs
src/groth16/prover.rs
src/groth16/tests/dummy_engine.rs
src/lib.rs
src/multicore.rs
src/multiexp.rs
src/test_utils.rs
tests/gpu_provers.rs
verifier-bench/Cargo.toml

A new environment variable `BELLMAN_GPU_FRAMEWORK` is introduced to select
CUDA or OpenCL if Bellperson is compiled with support for both.
Currently only the multiexp calculation is supported by CUDA, the FFT
calculation still runs on OpenCL.
BREAKING CHANGE: `gpu` feature is replaced with `cuda` and `opencl` feature.
The `gpu` feature is now split into two pieces, `opencl` and `cuda`, you can
compile the library with either or both.

feat: Add CUDA support

---

src/domain.rs
src/groth16/generator.rs
src/groth16/prover.rs

This required us to use `unsafe` casting, even though we don't actually make use of the abstraction 
anywhere. With it gone, so is the `unsafe` casting.
Depends on #205

refactor: remove `Group` abstraction in domain

---

src/groth16/prover.rs

groth16 prover: improve param loading

---

src/domain.rs
src/gpu/fft.rs
src/gpu/nogpu.rs
src/groth16/prover.rs

Implements specialized `fft_many` methods on `EvaluationDomain` to execute multiple FFTs in the groth16 prover more optimally.

perf: use multiple GPUs for FFTs

---

src/gadgets/sha256.rs

The existing test doesn't take into account the 1 bit padding required by
sha256.

Add test for full sha256 hash for constraint number

---

src/lc.rs
src/util_cs/metric_cs.rs
src/util_cs/mod.rs
src/util_cs/test_cs.rs

This PR adds a trait, `Comparable` and implements it for `MetricCS` and `TestConstraintSystem`. It allows for a more comprehensive comparison of synthesized constraint systems. This is especially helpful for cases where a constraint system is satisfied and verifies with public inputs — but the corresponding Groth16 proof fails to verify on those public inputs. This can be frustrating to debug…
After synthesizing a blank and non-blank constraint system, compare using the `delta` method, which returns a `Delta` enum which is either `Delta::Equal` or contains more specific information if they differ. When constraint systems differ only by the content of their constraints, it is extremely helpful to know which constraints differ.
`Delta::ConstraintMismatch` includes the first mismatched …

Add Comparable trait for comparing constraint systems.

---

src/util_cs/mod.rs

If a count mismatch is found when comparing constraint systems, this is valuable information; but it doesn't help identify the source of the mismatch.
This PR adds a boolean argument to `delta()`. If true, this signals that the comparison should ignore count mismatches, returning instead the first constraint mismatch (if any).

CS comparison ignore counts

---

Cargo.toml
README.md
src/gpu/utils.rs
tests/envvars1.rs
tests/envvars2.rs

Determining the number of cores is generally useful, so it was moved
to the rust-gpu-tools library. In order to set a custom GPU please
use the `RUST_GPU_TOOLS_CUSTOM_GPU` variable instead of
`BELLMAN_CUSTOM_GPU`.

fix: use Cuda cores determination from rust-gpu-tools

---

src/domain.rs
src/gpu/fft.rs
src/gpu/locks.rs
src/gpu/multiexp.rs

Instead on holding the GPU lock within each kernel implementation,
do the locking within the locked kernel abstraction.

refactor: move GPU lock into the locked kernel logic

---

src/domain.rs
src/gpu/locks.rs
src/gpu/nogpu.rs
src/groth16/prover.rs
src/multiexp.rs

The `log_d` parameter isn't used by the kernels, hence remote it.

refactor: remove no longer used log_d parameter

---

src/multiexp.rs

#261 moved DensityTracker into the `ec_gpu_gen` crate, breaking downstream usage. This PR re-exports to fix that.

Re-export DensityTracker.

---

Cargo.toml

`ec-gpu-gen` had a performance regression on OpenCL, update to at
least the version that has that fix.

chore: update ec-gpu-gen

---

src/groth16/proof.rs
src/groth16/prover.rs

Spliting into distinct G1 and G2 phases prepares for future changes
(when separate kernels are used for G1 and G2). This change doesn't
harm the performance. On 32GiB sectors the performance difference
between runs is bigger than with or without this change.
For micro benchmarks the `groth16::proof::test_with_bls12_381::serialization`
test was run. Below are the average prover times. The tests were always
run twice sequentially, the best run was used.
|    Version    | #GPUs |   CUDA    |  OpenCL   |
| :------------ | ----: | --------: | --------: |
| prior         |     1 | 167.665ms | 379.428ms |
| this change   |     1 | 165.677ms | 370.912ms |
| prior         |     4 | 197.071ms | 1155.59ms |
| this change   |     4 | 198.019ms | 1081.05ms |
The command the tests were run with: …

refactor: do G2 calculations after G1 calculations

---

.circleci/config.yml
Cargo.toml
build.rs
src/domain.rs
src/gpu/locks.rs
src/gpu/mod.rs
src/gpu/multiexp.rs
src/gpu/nogpu.rs
src/groth16/ext.rs
src/groth16/generator.rs
src/groth16/prover.rs
src/groth16/tests/dummy_engine.rs
src/multiexp.rs
verifier-bench/Cargo.toml

The FFT and Multiexp kernels operates on fields instead of an engine.
For Multiexp it means that for BLS12-381 we need two separate kernels,
one for G1 and one for G2.
The kernel generation is no longer set via feature flags in `ec-gpu-gen`,
but instead it is directly specified in this library in the `build.rs`.
BREAKING CHANGE: upgrade to blstrs 0.6.0
`blstrs` version 0.6.0 is pinned to `blst` 0.3.10. All dependencies
need to be at the same version. Hence doing a breaking change release
is needed.

fix: make it work with latest GPU kernels

---

Cargo.toml
release.toml

Cargo-release had two parameter name changes which need to be updated in order to publish the new release. 
pro-release-commit-message => post-release-commit-message
no-dev-version => dev-version

Bellperson Release v0.23.0

---

Cargo.toml
src/groth16/aggregate/srs.rs
src/groth16/mapped_params.rs
src/groth16/mod.rs
src/groth16/params.rs
src/groth16/verifying_key.rs

The `wasm` feature was introduced as `getrandom` needs the `js` feature
in order to compile for `wasm32-unknown-unknown`. A better fix is to disable
the default features of `rand` instead. This way the `wasm` feature is no
longer needed.
For compiling on WebAssembly also the `memmap` feature was introduced. Remove
that feature and replace it with target architecture flags, that exclude
memmap related functions when compiled for wasm.
This lowers the maintenance burden as WebAssembly is no longer a special case.
Thanks @samuelburnham for the code that made the removal of `memmap` feature
possible.
BREAKING CHANGE: `wasm` and `memmap` features are removed
If you're targetting WASM and using `bellperson` as a dependency, prior to this
change you'd have included it as:
bellperson = { version …

fix: remove wasm feature

---

Cargo.toml

bitvec 0.22 does no longer build, due to funty 1.2 being yanked. bitvec wasn't actually used directly by this library anymore. Upgrade to ec-gpu-gen 0.5 which is using bitvec 1.0.1.

fix: upgrade bitvec

---

Cargo.toml

This update is needed as bitvec 0.22.3 is requiring funty 1.2 which was yanked.
`bitvec` isn't a direct dependency of bellperson anymore. The upgrade to `ec-gpu-gen` v0.3.1 is done, as it;s the bugfix release that upgrades its `bitvec` from v0.22 to v1.0.1.

fix: make sure bitvec v1.0.1 is used

---

Cargo.toml
src/gpu/error.rs
src/gpu/locks.rs
tests/gpu_provers.rs

Due to refactorings, the `PriorityLock::should_break()` logic was quite confusing and used the wrong way. Make it work correctly while simplifying the logic.
This commit also removes `PriorityLock` from the public API as it isn't really needed.
Tweak some values in the parallel prover test, so that aborting a low priority kernel from running on the GPU happens more frequently.
It needs a newer version of `ec-gpu-gen`, else it would cause panics
(which are not fatal, as they happen within a thread. Though, they
still show up in the logs).
Fixes #291.

fix: make priority locking work again

---

README.md
src/gpu/locks.rs

original implementation lock bellman.gpu.lock to lock all GPUs in default. And in my test with cuda
single 3080 for C2: 15m52s
dual 3080 for C2: 12m36s
so i think it's better to let user to choice if they need to use all GPUs for one C2 task.
a environment named BELLPERSON_GPUS_PER_LOCK is introduced to let user to set.
if BELLPERSON_GPUS_PER_LOCK is not set, then we use all GPUs for one C2, just like current implementation;
if BELLPERSON_GPUS_PER_LOCK == 0, just like above;
if BELLPERSON_GPUS_PER_LOCK > 0, use BELLPERSON_GPUS_PER_LOCK GPUs (up to devices.len()) for one C2 task.
https://github.com/filecoin-project/bellperson/pull/298: circleci not work properly, so i re-create this one.

Support to lock GPUs for each task according to BELLPERSON_GPUS_PER_LOCK environment (circleci of #298 not work properly, so i re-create this one)

---

src/gadgets/sha256.rs

The `sha256_compression_function()` function is now public, which was requested at https://github.com/filecoin-project/bellperson/issues/301.
Closes #301.

feat: make sha256_compression_function public

---

src/gpu/locks.rs

Prior to this change, the GPU was disabled, when the `BELLMAN_NO_GPU` environment variable was set to any value, even when set to 0.
Fixes #249.

fix: disable GPU if BELLMAN_NO_GPU=0

---

src/constraint_system.rs
src/util_cs/mod.rs
src/util_cs/test_cs.rs
src/util_cs/witness_cs.rs

This PR adds some new ConstraintSystem methods. These methods are intended to only be implemented by or called on ConstraintSystems that are also designated as witness generators. Such ConstraintSystems will signal this by implementing and returning true from `is_witness_generator()`. 
A minimal `WitnessCS` suitable for this purpose is also provided, as is a `SizedWitness` trait which should be implemented by objects (for example, implementers of `Circuit`) that choose to offer efficient witness-generation.
In this context, 'efficient witness generation' likely bypasses the usual, flexible mechanism used to specify `bellperson` circuits. Although convenient, this mechanism conflates synthesis and witness generation in ways that can add significant overhead.
Initial synthesis benchmarks in …

Add WitnessCS, SizedWitness, and related ConstraintSystem methods.

---

Cargo.toml
src/constraint_system.rs
src/groth16/prover.rs
src/util_cs/witness_cs.rs

See https://github.com/filecoin-project/bellperson/pull/309 for context:
- the signature of ConstraintSystem::extend prevents the correctness of an `impl<[...]CS: ConstraintSystem<Scalar>> ConstraintSystem<S> for &'cs mut CS`
- the upgrade to ec-gpu-gen 0.7.0 allows a change in signature of ConstraintSystem::extend, and re-establishing correct behavior for this convenience impl.
- this change is not backwards-compatible, as the former implementation had observable incorrect behavior (in particular deferral to default trait fields) that are not reproduced here.
This should re-target main once #309 is merged, ~~or can be merged therein.~~

fix: Upgrade ec-gpu-gen 0.7.0, make ConstraintSystem::extend by-ref

---

src/groth16/proof.rs

`proof_bytes` is untrusted, user input. If the input is malformed, return an error instead of panicking.

read_many: return an error instead of a panic

---

.circleci/config.yml

Use a stock docker image instead of a custom one. Also use smaller machines where it makes sense to reduce costs.

chore: update CI

---

README.md

The README now mentions that Turing is the lowest supported architecture.

docs: clarify NVIDIA minimum architecture

---

src/groth16/prover/supraseal.rs

Verified to work in https://github.com/supranational/supra_seal/pull/39

Switch to a more general supraseal_c2::generate_groth16_proofs interface.

---

.github/workflows/ci.yml

Reverts filecoin-project/bellperson#324
This is related to https://github.com/filecoin-project/github-mgmt/issues/132. This is a temporary revert. We need to first get back on hosted runners before getting on FilOz's self-hosted runners, because `self-hosted` tag is too permissive and would start matching any FilOz's runners as soon as I allow this repository to access them.

Revert "Switch to self hosted CI"

---

src/groth16/aggregate/commit.rs
src/groth16/aggregate/proof.rs

---
**Description:**  
This pull request corrects a minor typo in the documentation comment for the `Key` struct in `commit.rs`.  
- Changed "instanciated" to "instantiated" for improved clarity and professionalism.
---

Fix Typo in Commit Key Documentation
